spring:
 application:
  name: Config-Prod
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 172.20.10.3
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
